# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20170131_1213'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='expo_tags', to='nucleo.Tag'),
        ),
    ]
