# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20170131_1314'),
        ('eventos', '0002_expo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expo',
            name='sala',
        ),
        migrations.AddField(
            model_name='actividad',
            name='fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Galeria'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='imagen',
            field=models.FileField(blank=True, upload_to='license'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Lugar'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='realizador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='actividad_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('Educación', 'EDUCACION'), ('Master Class', 'MASTER CLASS'), ('Proyección', 'PROYECCION')], default='EDUCACION', max_length=30),
        ),
        migrations.AddField(
            model_name='expo',
            name='autor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expo',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expo',
            name='galeria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Galeria'),
        ),
        migrations.AddField(
            model_name='expo',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Lugar'),
        ),
    ]
