# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['actividad'],
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['articulo'],
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['galeria'],
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galería',
            },
        ),
        migrations.CreateModel(
            name='Inauguracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inauguracion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['inauguracion'],
                'verbose_name': 'Inauguración',
                'verbose_name_plural': 'Inauguraciones',
            },
        ),
        migrations.CreateModel(
            name='Incrustado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incrustado', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['incrustado'],
                'verbose_name': 'Incrustados',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('Sala', 'SALA'), ('Patio', 'PATIO')], default='SALA', max_length=50)),
            ],
            options={
                'ordering': ['lugar'],
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.AlterModelOptions(
            name='expo',
            options={'ordering': ['expo'], 'verbose_name': 'Exposición', 'verbose_name_plural': 'Exposiciones'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
