# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20170131_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.RemoveField(
            model_name='expo',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Inauguracion',
        ),
        migrations.AlterModelOptions(
            name='incrustado',
            options={'ordering': ['incrustado'], 'verbose_name': 'Incrustados', 'verbose_name_plural': 'Incrustados'},
        ),
        migrations.DeleteModel(
            name='Expo',
        ),
    ]
