# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20170131_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['galeria'], 'verbose_name': 'Galería', 'verbose_name_plural': 'Galerías'},
        ),
    ]
