# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20170131_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='galerias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Galeria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articulo_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='texto',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
