# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20170131_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='./static/img/galerias')),
                ('texto', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Imágenes',
                'verbose_name': 'Imagen',
                'ordering': ['imagen'],
            },
        ),
    ]
